language: ruby
dist: xenial
services:
  - postgresql
env:
  matrix:
    - DATABASE_ADAPTER=sqlite3
    - DATABASE_ADAPTER=postgresql
rvm:
  - ruby-head
  - 2.7.2
  - 2.6.6
  - 2.5.8
  - 2.4.10
gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile
matrix:
  exclude:
    - rvm: 2.7.2
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/rails_6_0.gemfile
cache:
  directories:
    - /home/travis/.rvm/gems/ruby-2.7.2
    - /home/travis/.rvm/gems/ruby-2.6.6
    - /home/travis/.rvm/gems/ruby-2.5.8
    - /home/travis/.rvm/gems/ruby-2.4.10
# Source: <https://docs.travis-ci.com/user/languages/ruby/#bundler-20>
before_install:
  - gem update --system --force --no-document
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2' --no-document
install: "bundle install --jobs=3 --retry=3"
script: "bundle exec rake"
branches:
  only:
    - master
