language: ruby
sudo: false
script: "bundle exec rake"

branches:
  except:
    - site
    - gh-pages

rvm:
  - 2.0.0
  - 2.1.4
  - rbx-19mode
  - jruby-19mode

gemfile:
  - gemfiles/4.0.0.gemfile
  - gemfiles/4.0.1.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: jruby-19mode
