script: "bundle exec rake spec cucumber"

rvm:
  - 1.9.2
  - 1.9.3

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: jruby-19mode
  include:
    - rvm: 2.0.0
      gemfile: gemfiles/3.2.gemfile
    - rvm: rbx-19mode
      gemfile: gemfiles/3.2.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/3.2.gemfile
